version: "3.7"

volumes:
  api-volume:
    name: api-volume

networks:
  api-network:
    name: api-network

services:
  postgres:
    image: "postgres:13.1"
    restart: on-failure
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - api-volume:/var/lib/postgresql/data
      - ./db/scripts:/docker-entrypoint-initdb.d
    networks:
      - api-network

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - ./:/app
    networks:
      - api-network
    entrypoint: ["/bin/bash", "./scripts/entrypoint.dev.sh"]
